config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resources :tshirts
    get 'checkout_id=:tshirt_id', to: "checkouts#new", as: :new_checkout
    post 'checkout/order=:id', to: "checkouts#order", as: :new_order
    get 'checkout/order=:id/success', to: "checkouts#success", as: :successful_order

  resources :checkouts, except: [:new], path: 'checkout', param: :id_encrypted do
    resources :payments, only: [:create]
  end


  require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkout.rb
class Checkout < ApplicationRecord
  belongs_to :tshirt
  belongs_to :user, optional: true

  monetize :price_cents

end

app/models/printful.rb
class Printful < ApplicationRecord
end

app/models/shirt_config.rb
class ShirtConfig < ApplicationRecord
  belongs_to :tshirt
  belongs_to :user
end

app/models/tshirt.rb
class Tshirt < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tshirts
  has_many :checkouts


  protected

  def password_required?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/checkouts_controller.rb
require 'money'

class CheckoutsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :new, :show, :order, :success]

  def index
  end

  def new
    @checkout = Checkout.new

    @tshirt = Tshirt.find(params[:tshirt_id])
    @checkout.tshirt_id = @tshirt.id

    @checkout.picture_front = "Front"
    @checkout.picture_back = "Back"
    @checkout.price = Money.new(1995, "EUR")

    @checkout.status = "pending"

    @checkout.id_encrypted = SecureRandom.urlsafe_base64

    @checkout.save

    puts @checkout.id
    puts @checkout.id_encrypted

    redirect_to checkout_path(@checkout.id_encrypted)
  end

  def show
    @checkout = Checkout.find_by_id_encrypted(params["id_encrypted"])
    @user = User.new()
    @checkout.user = @user
  end

  def order
    @checkout = Checkout.find(params[:id])
    @user = User.new(user_params)
    @user.country_code = "DE"
    @user.save

    @checkout.user = @user

    p @user.errors.messages # debug

    @checkout.save

  end

  def success
    @checkout = Checkout.find(params[:id])

    PostOrderJob.perform_later(@checkout.id)

  end



  private

  def user_params
    p = params.require(:checkout).permit!

    @user_params = p[:user]
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @tshirt = Tshirt.new
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_vars

  def new
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,
      amount:       @checkout.price_cents,
      description:  "Bezahlung für Elternshirt #{@checkout.tshirt.id} für Bestellung #{@checkout.id}",
      currency:     @checkout.price.currency
    )

    @user.stripeid = customer.id

    @checkout.update(payment: charge.to_json, status: 'paid')
    redirect_to successful_order_path(@checkout)

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_order_path(@checkout)

  raise
  end

private
  def set_vars
    # @checkout = current_user.checkouts.where(status: 'pending').find(params[:checkout_id])

    @checkout = Checkout.find(params[:checkout_id_encrypted])
    @user = @checkout.user
  end

end

app/controllers/tshirts_controller.rb
class TshirtsController < ApplicationController

  skip_before_action :authenticate_user! #, only: [:new, :show, :create]


  def create
    @tshirt = Tshirt.new(tshirt_params)
    @tshirt.birth_date = params[:birth_date]
    @tshirt.user = current_user


# raise

    if @tshirt.save
      respond_to do |format|
        format.html { render "tshirts/show" }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render "tshirts/new" }
        format.js  # <-- idem
      end
    end
  end

  def show
    @tshirt = Tshirt.new(tshirt_params)
  end

  def update
    @tshirt = Tshirt.find(params[:id])
    @tshirt.update(tshirt_update_params)

    redirect_to new_checkout_path(@tshirt)
  end

private

  def tshirt_params
    params.require(:tshirt).permit(:gender, :child_name)
  end

  def tshirt_update_params
    params.require(:tshirt).permit(:color, :size, :back1, :back2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/checkouts/order.html.erb
<% @user.name %>
<% @user.email %>
<% @user.address1 %>
<% @user.address2 %>
<% @user.city %>
<% @user.zip %>
<% @user.password %>


<div class="container">
  <h1>Bestellung abschließen</h1>
  <div class="shirt-summary">
    <h3>Dein Elternshirt: </h3>
    <p>Preis: <%= humanized_money_with_symbol @checkout.price %> inkl. Versandgebühren</h3>
    <p>Größe: <%= @checkout.tshirt.size %> </p>
  </div>
  <div class="shipping-summary">
    <h3>Versand an:</h3>
    <p><%= @user.name %></p>
    <p><%= @user.email %></p>
    <p><%= @user.address1 %></p>
    <p><%= @user.address2 %></p>
    <p><%= @user.city %></p>
    <p><%= @user.zip %></p>
    <p><%= @user.password %></p>
  </div>

  <%= form_tag checkout_payments_path(@checkout) do %>

    <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
    <% end %>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-name="Mein Elternshirt (Tshirt Nr. <%= @checkout.tshirt.id %>)"
      data-email="<%= @user.email %>"
      data-description="Elternshirt <%= @checkout.tshirt.id %>"
      data-amount="<%= @checkout.price_cents %>"
      data-currency="<%= @checkout.price.currency %>">
    </script>

  <% end %>

</div>

app/views/checkouts/show.html.erb
<%# @checkout.user.email %>
<%= @checkout.tshirt.gender %>
<%= @checkout.tshirt.child_name %>
<%= @checkout.tshirt.birth_date %>

<div class="container">
  <%= simple_form_for @checkout, url: new_order_path(@checkout), method: :post do |f| %>

    <%= f.simple_fields_for @user do |u| %>

    <h3>Versandinformationen (notwendig)</h3>
      <%= u.label "Name" %>
      <%= u.input :name, required: true, label: false %>
      <%= u.label "Email" %>
      <%= u.input :email, required: false, label: false %>
      <%= u.label "Straße, Hausnummer" %>
      <%= u.input :address1, required: true, label: false %>
      <%= u.label "Weitere Addressinformationen" %>
      <%= u.input :address2, required: false, label: false %>
      <%= u.label "Stadt" %>
      <%= u.input :city, required: true, label: false %>
      <%# u.label "Bundesland" %>
      <%# u.input :state_code, required: true, label: false %>
      <%# u.label "Land" %>
      <%# u.input :country_code, required: true, label: false %>
      <%= u.label "Postleitzahl" %>
      <%= u.input :zip, required: true, label: false %>

    <h3>Erstelle ein Nutzerkonto (optional)</h3>
      <%= u.label "Passwort" %>
      <%= u.input :password, required: false, hint: ("Mindestlänge: #{@minimum_password_length} Zeichen" if @minimum_password_length), label: false %>
      <%= u.label "Passwort bestätigen" %>
      <%= u.input :password_confirmation, required: false, label: false %>
    <% end %>

  <%= f.submit :"Weiter zur Zahlung" %>

  <% end %>
</div>

app/views/checkouts/success.html.erb
Payment <%= if @checkout.status = "paid"
    "successful"
  else
    "failed"

  end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="main-container">
        <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="config">
    <div class="cta">
      <h3>Konfiguriere jetzt Dein Shirt in 30 Sekunden.</h3>
    </div>
    <div class="choice">
      <%= render '/tshirts/form', tshirt: @tshirt %>
    </div>
    <%= render '/tshirts/shirt', tshirt: @tshirt %>
  </div>
  <div class="usp">
    <div class="usp-item-group">
      <div class="usp-item">
        <span><i class="fas fa-child"></i></span><p>Zeig der Welt, dass Du stolz auf Dein Kind bist</p>
      </div>
      <div class="usp-item">
        <span><i class="far fa-smile"></i></span><p>Bestelle jetzt Dein 100% individuelles Elternshirt</p>
      </div>
    </div>
    <div class="usp-item-group">
      <div class="usp-item">
        <span><i class="fas fa-trophy"></i></span><p>Dein ganz besonderes Shirt, in Premiumqualität</p>
      </div>
      <div class="usp-item">
        <span><i class="fas fa-gift"></i></span><p>Auch als Geschenk eine große Freude für alle Eltern!</p>
      </div>
    </div>
  </div>
</div>
<%= content_for :after_js do %>
  <%= javascript_pack_tag 'datepicker' %>
  <%= javascript_pack_tag 'shirtFrontPrint' %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#">Impressum</a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fa fa-heart"></i> in Berlin
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <p class="nav-head">Elternshirt<span class="das-shirt"> das Shirt </span><span class="underline">nur für Eltern</span></p>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
      <% end %>

    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        <% else %>
          <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tshirts/_form.html.erb
<%= simple_form_for tshirt, wrapper: :inline_form, url: tshirts_path(@tshirt), method: :post, html: { class: 'form-inline'} do |f| %>
<div class="form-gender">
  <%= f.label "Ich bin" %>
  <%= f.input :gender, collection: ['Mama', 'Papa'], id: "gender-dropdown", selected: "Papa" %>
</div>
<div class="form-name">
  <%= f.label "Mein Kind heißt" %>
  <%= f.input :child_name, input_html: {value: "Kevin"} %>
</div>
<div class="form-birthdate">
  <%= f.label "Geburtsdatum" %>
  <div class='input-group date' id='datetimepicker2'>
    <%= text_field_tag(:date, Date.today.strftime("%d/%m/%Y"), class: 'form-control', name: "birth_date") %>
    <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
    </span>
  </div>
</div>
<%= f.submit :"Weiter", class: "btn-continue" %>
<% end %>

app/views/tshirts/_form_extended.html.erb
<%= simple_form_for tshirt, url: tshirt_path(@tshirt), method: :put, html: { id: "extended_shirt_form" } do |f| %>
<div class="form-color">
  <%= f.label "Farbe" %>
  <%= f.input :color, collection: ['Weiss', 'Navy', 'Schwarz'], id: "color-dropdown", selected: "Weiss", label: false %>
  <%= f.label "Größe" %>
  <%= f.input :size, collection: ['S', 'M', 'L', 'XL', '2XL', '3XL'], id: "size-dropdown", selected: "S", label: false %>
</div>
<div class="form-back">
  <div class="ctrl-back">
    <%= f.label "Optional: Rückenbeschriftung" %>
    <button id="btn-back">Rücken</button>
    <button id="btn-front" hidden="true">Vorne</button>
  </div>
  <%= f.input :back1, label: false, input_html: {value: "Zeile 1", onfocus: "if (this.value=='Zeile 1') this.value='';", onfocusout: "if (this.value=='') this.value='Zeile 1';" } %>
  <%= f.input :back2, label: false, input_html: {value: "Zeile 2", onfocus: "if (this.value=='Zeile 2') this.value='';", onfocusout: "if (this.value=='') this.value='Zeile 2';" }  %>
  <%# f.input :back3, label: false, input_html: {value: "Zeile 3", onfocus: "if (this.value=='Zeile 3') this.value='';", onfocusout: "if (this.value=='') this.value='Zeile 3';"   }  %>
</div>
<br>
<div class="checkout">
  <h4>Jetzt bestellen:</h4>
  <div class="ctrl-checkout">
    <!-- <span><h5>Preis: 19.95€ <br></h5><p>exkl. Versand</p></span> -->
    <span><%= f.submit "Weiter", class: "btn-checkout" %></span>
  </div>
</div>
<% end %>

app/views/tshirts/_shirt.html.erb
<div class="shirt">
  <div class="shirt-image shirt-white">
  </div>
  <div class="shirt-text">
    <% if (@tshirt.gender).nil? %>
      <p id="shirt-text-gender">Stolzer Papa</p>
      <p id="shirt-text-name">von Kevin</p>
      <p id="shirt-text-date"></p>
    <% else %>
      <% if @tshirt.gender == "Papa" %>
        <p id="shirt-text-gender">Stolzer <%= @tshirt.gender %></p>
      <% else %>
        <p id="shirt-text-gender">Stolze <%= @tshirt.gender %></p>
      <% end %>
      <p id="shirt-text-name">von <%= @tshirt.child_name %></p>
      <p id="shirt-text-date"><%= @tshirt.birth_date.strftime("%d/%m/%Y") %></p>
    <% end %>
  </div>
</div>

app/views/tshirts/_shirt_extended.html.erb
<div class="shirt" id="shirt-extended">
  <div class="shirt-image shirt-white">
  </div>
  <div class="shirt-text">
    <% if (@tshirt.gender).nil? %>
      <p id="shirt-text-gender">Stolzer Papa</p>
      <p id="shirt-text-name">von Kevin</p>
      <p id="shirt-text-date"></p>
    <% else %>
      <% if @tshirt.gender == "Papa" %>
        <p id="shirt-text-gender">Stolzer <%= @tshirt.gender %></p>
      <% else %>
        <p id="shirt-text-gender">Stolze <%= @tshirt.gender %></p>
      <% end %>
      <p id="shirt-text-name">von <%= @tshirt.child_name %></p>
      <p id="shirt-text-date"><%= @tshirt.birth_date.strftime("%d/%m/%Y") %></p>
    <% end %>
  </div>
</div>

app/views/tshirts/_shirt_extended_back.html.erb
<div class="shirt shirt-back" id="shirt-extended">
  <div class="shirt-image shirt-white">
  </div>
  <div class="shirt-text">
    <p id="shirt-back-1"></p>
    <p id="shirt-back-2"></p>
  </div>
</div>

app/views/tshirts/create.js.erb
function refreshForm(innerHTML) {
  const newTshirtForm = document.getElementById('new_tshirt');
  newTshirtForm.innerHTML = innerHTML;
}

function addTshirt() {
  // const newTshirtForm = document.getElementById('new_tshirt');
  const gender = document.getElementById('tshirt_gender').options[document.getElementById('tshirt_gender').selectedIndex].text;
  const child_name = document.getElementById('tshirt_child_name').value;
  const birth_date = document.getElementById('date').value;


}

<% if @tshirt.errors.any? %>
  refreshForm('<%= j render "tshirts/form", tshirt: @tshirt %>');
<% else %>
  addTshirt();
<% end %>

app/views/tshirts/new.html.erb
<%= @tshirt.gender %>
<%= @tshirt.child_name %>
<%= @tshirt.birth_date.strftime("%d, %m, %y") %>

app/views/tshirts/show.html.erb
<div class="banner">
  <div class="config">
    <div class="cta">
      <h3>Gib Deinem Shirt den letzten Feinschliff!</h3>

    </div>
    <div class="choice-container">
      <div class="tshirt-container">
        <div class="front">
          <%= render '/tshirts/shirt_extended', tshirt: @tshirt %>
        </div>
        <div class="back">
          <%= render '/tshirts/shirt_extended_back', tshirt: @tshirt %>
        </div>
      </div>
      <div class="choice">
        <%= render '/tshirts/form_extended', tshirt: @tshirt %>
      </div>
    </div>
  </div>
  <div class="usp">
    <div class="usp-item-group">
      <div class="usp-item">
        <span><i class="fas fa-child"></i></span><p>Zeig der Welt, dass Du stolz auf Dein Kind bist</p>
      </div>
      <div class="usp-item">
        <span><i class="far fa-smile"></i></span><p>Bestelle jetzt Dein 100% individuelles Elternshirt</p>
      </div>
    </div>
    <div class="usp-item-group">
      <div class="usp-item">
        <span><i class="fas fa-trophy"></i></span><p>Dein ganz besonderes Shirt, in Premiumqualität</p>
      </div>
      <div class="usp-item">
        <span><i class="fas fa-gift"></i></span><p>Auch als Geschenk eine große Freude für alle Eltern!</p>
      </div>
    </div>
  </div>
</div>
<%= content_for :after_js do %>
  <%= javascript_pack_tag 'flip' %>
  <%# javascript_pack_tag 'shirtBackPrint' %>
<% end %>